import * as stylex from "@stylexjs/stylex";
import { styles } from "./site.stylex";

export type XStyle = stylex.StyleXStyles<Record<string, string | number | null>>;
export type StyledProps<T> = T & { xstyle?: XStyle };

const markers = {
  appCourseCodePageStyle1: "sx-appCourseCodePageStyle1",
  appCourseCodePageStyle2: "sx-appCourseCodePageStyle2",
  appCourseCodePageStyle3: "sx-appCourseCodePageStyle3 ui-text-defined",
  appCourseCodePageStyle4: "sx-appCourseCodePageStyle4 ui-text-defined",
  appCourseCodePageStyle5: "sx-appCourseCodePageStyle5 ui-text-defined",
  appCourseCodePageStyle6: "sx-appCourseCodePageStyle6 ui-border-b",
  appCourseCodePageStyle7: "sx-appCourseCodePageStyle7 ui-group ui-text-defined",
  appCourseCodePageStyle8: "sx-appCourseCodePageStyle8",
  appCourseCodePageStyle9: "sx-appCourseCodePageStyle9 ui-text-defined",
  appCourseCodePageStyle10: "sx-appCourseCodePageStyle10",
  appCourseCodePageStyle11: "sx-appCourseCodePageStyle11",
  appCourseCodePageStyle12: "sx-appCourseCodePageStyle12",
  appCourseCodePageStyle13: "sx-appCourseCodePageStyle13",
  appCourseCodePageStyle14: "sx-appCourseCodePageStyle14 ui-text-defined",
  appCourseCodePageStyle15: "sx-appCourseCodePageStyle15 ui-text-defined",
  appCourseCodePageStyle16: "sx-appCourseCodePageStyle16 ui-text-defined",
  appCourseCodePageStyle17: "sx-appCourseCodePageStyle17 ui-text-defined",
  appCourseCodePageStyle18: "sx-appCourseCodePageStyle18 ui-text-defined",
  appCourseCodePageStyle19: "sx-appCourseCodePageStyle19 ui-text-defined",
  appCourseCodePageStyle20: "sx-appCourseCodePageStyle20",
  appCourseCodePageStyle21: "sx-appCourseCodePageStyle21",
  appCourseCodePageStyle22: "sx-appCourseCodePageStyle22 ui-text-defined",
  appCourseCodePageStyle23: "sx-appCourseCodePageStyle23 ui-text-defined",
  appCourseCodePageStyle24: "sx-appCourseCodePageStyle24",
  appCourseCodePageStyle25: "sx-appCourseCodePageStyle25",
  appCourseCodePageStyle26: "sx-appCourseCodePageStyle26",
  appCourseCodePageStyle27: "sx-appCourseCodePageStyle27 ui-text-defined",
  appCourseCodePageStyle28: "sx-appCourseCodePageStyle28 ui-text-defined",
  appCourseCodePageStyle29: "sx-appCourseCodePageStyle29 ui-text-defined",
  appCourseCodePageStyle30: "sx-appCourseCodePageStyle30",
  appCourseCodePageStyle31: "sx-appCourseCodePageStyle31 ui-text-defined",
  appCourseCodePageStyle32: "sx-appCourseCodePageStyle32",
  appCourseCodePageStyle33: "sx-appCourseCodePageStyle33",
  appCourseCodePageStyle34: "sx-appCourseCodePageStyle34 ui-border-b",
  appCourseCodePageStyle35: "sx-appCourseCodePageStyle35 ui-text-defined",
  appCourseCodePageStyle36: "sx-appCourseCodePageStyle36",
  appCourseCodePageStyle37: "sx-appCourseCodePageStyle37",
  appCourseCodePageStyle38: "sx-appCourseCodePageStyle38 ui-text-defined",
  appDegreeSlugPageStyle2: "sx-appDegreeSlugPageStyle2 ui-border-b",
  appDegreeSlugPageStyle3: "sx-appDegreeSlugPageStyle3",
  appDegreeSlugPageStyle4: "sx-appDegreeSlugPageStyle4 ui-text-defined",
  appDegreeSlugPageStyle5: "sx-appDegreeSlugPageStyle5",
  appDegreeSlugPageStyle6: "sx-appDegreeSlugPageStyle6",
  appDegreeSlugPageStyle7: "sx-appDegreeSlugPageStyle7 ui-text-defined",
  appDegreeSlugPageStyle8: "sx-appDegreeSlugPageStyle8 ui-text-defined",
  appDegreeSlugPageStyle9: "sx-appDegreeSlugPageStyle9",
  appDegreeSlugPageStyle10: "sx-appDegreeSlugPageStyle10",
  appDegreeSlugPageStyle11: "sx-appDegreeSlugPageStyle11 ui-border-b",
  appDegreeSlugPageStyle12: "sx-appDegreeSlugPageStyle12 ui-text-defined",
  appDegreeSlugPageStyle13: "sx-appDegreeSlugPageStyle13 ui-text-defined",
  appDegreeSlugPageStyle14: "sx-appDegreeSlugPageStyle14",
  appDegreeSlugPageStyle15: "sx-appDegreeSlugPageStyle15",
  appDegreeSlugPageStyle16: "sx-appDegreeSlugPageStyle16 ui-text-defined",
  appDegreeSlugPageStyle17: "sx-appDegreeSlugPageStyle17",
  appDegreeSlugPageStyle18: "sx-appDegreeSlugPageStyle18 ui-border-t",
  appDegreeSlugPageStyle19: "sx-appDegreeSlugPageStyle19 ui-text-defined",
  appDegreeSlugPageStyle21: "sx-appDegreeSlugPageStyle21 ui-text-defined",
  appDegreeSlugPageStyle22: "sx-appDegreeSlugPageStyle22 ui-text-defined",
  appDegreeSlugPageStyle23: "sx-appDegreeSlugPageStyle23",
  appDegreeSlugPageStyle24: "sx-appDegreeSlugPageStyle24",
  appDegreeSlugPageStyle25: "sx-appDegreeSlugPageStyle25 ui-text-defined",
  appDegreeSlugPageStyle26: "sx-appDegreeSlugPageStyle26 ui-text-defined",
  appDegreeSlugPageStyle27: "sx-appDegreeSlugPageStyle27",
  appDegreeSlugPageStyle28: "sx-appDegreeSlugPageStyle28",
  appDegreeSlugPageStyle29: "sx-appDegreeSlugPageStyle29 ui-text-defined",
  appDegreeSlugPageStyle30: "sx-appDegreeSlugPageStyle30 ui-border-b ui-text-defined",
  appDegreeSlugPageStyle31: "sx-appDegreeSlugPageStyle31",
  appDegreeSlugPageStyle32: "sx-appDegreeSlugPageStyle32",
  appDegreeSlugPageStyle33: "sx-appDegreeSlugPageStyle33 ui-text-defined",
  appDegreeSlugPageStyle36: "sx-appDegreeSlugPageStyle36 ui-text-defined",
  appDegreeSlugPageStyle37: "sx-appDegreeSlugPageStyle37",
  appDegreeSlugPageStyle38: "sx-appDegreeSlugPageStyle38 ui-text-defined",
  appDegreeSlugPageStyle40: "sx-appDegreeSlugPageStyle40 ui-text-defined",
  appDegreeSlugPageStyle41: "sx-appDegreeSlugPageStyle41",
  appDegreeSlugPageStyle42: "sx-appDegreeSlugPageStyle42 ui-group",
  appDegreeSlugPageStyle43: "sx-appDegreeSlugPageStyle43 ui-text-defined",
  appDegreeSlugPageStyle44: "sx-appDegreeSlugPageStyle44",
  appDegreeSlugPageStyle45: "sx-appDegreeSlugPageStyle45 ui-text-defined",
  appDegreeSlugPageStyle46: "sx-appDegreeSlugPageStyle46",
  appDegreeSlugPageStyle47: "sx-appDegreeSlugPageStyle47 ui-text-defined",
  appDegreeSlugPageStyle50: "sx-appDegreeSlugPageStyle50 ui-text-defined",
  appDegreeSlugPageStyle54: "sx-appDegreeSlugPageStyle54 ui-text-defined",
  appDegreeSlugPageStyle56: "sx-appDegreeSlugPageStyle56 ui-text-defined",
  appDegreeSlugPageStyle59: "sx-appDegreeSlugPageStyle59 ui-text-defined",
  appDegreeSlugPageStyle69: "sx-appDegreeSlugPageStyle69 ui-text-defined",
  appDegreeSlugPageStyle70: "sx-appDegreeSlugPageStyle70 ui-group",
  appDegreeSlugPageStyle71: "sx-appDegreeSlugPageStyle71 ui-text-defined",
  appDegreeSlugPageStyle72: "sx-appDegreeSlugPageStyle72",
  appDegreeSlugPageStyle73: "sx-appDegreeSlugPageStyle73",
  appDegreeSlugPageStyle74: "sx-appDegreeSlugPageStyle74 ui-text-defined",
  appDegreeSlugPageStyle75: "sx-appDegreeSlugPageStyle75 ui-text-defined",
  appDegreeSlugPageStyle77: "sx-appDegreeSlugPageStyle77 ui-text-defined",
  appDegreeSlugPageStyle78: "sx-appDegreeSlugPageStyle78",
  appDegreeSlugPageStyle79: "sx-appDegreeSlugPageStyle79 ui-border-t",
  appDegreeSlugPageStyle80: "sx-appDegreeSlugPageStyle80",
  appDegreeSlugPageStyle81: "sx-appDegreeSlugPageStyle81 ui-group-item",
  appDegreeSlugPageStyle82: "sx-appDegreeSlugPageStyle82",
  appDegreeSlugPageStyle83: "sx-appDegreeSlugPageStyle83 ui-text-defined",
  appDegreeSlugPageStyle84: "sx-appDegreeSlugPageStyle84 ui-text-defined",
  appDegreeSlugPageStyle86: "sx-appDegreeSlugPageStyle86",
  appDegreeSlugPageStyle88: "sx-appDegreeSlugPageStyle88 ui-border-b ui-text-defined",
  appDegreeSlugPageStyle89: "sx-appDegreeSlugPageStyle89",
  appDegreeSlugPageStyle90: "sx-appDegreeSlugPageStyle90",
  appDegreePageStyle1: "sx-appDegreePageStyle1 ui-text-defined",
  appDegreePageStyle2: "sx-appDegreePageStyle2",
  appDegreePageStyle3: "sx-appDegreePageStyle3 ui-text-defined",
  appDegreePageStyle4: "sx-appDegreePageStyle4 ui-text-defined",
  appDegreePageStyle6: "sx-appDegreePageStyle6",
  appDegreePageStyle7: "sx-appDegreePageStyle7 ui-text-defined",
  appDegreePageStyle8: "sx-appDegreePageStyle8 ui-text-defined",
  appDegreePageStyle9: "sx-appDegreePageStyle9",
  appDegreePageStyle10: "sx-appDegreePageStyle10 ui-group",
  appDegreePageStyle11: "sx-appDegreePageStyle11",
  appDegreePageStyle12: "sx-appDegreePageStyle12",
  appDegreePageStyle13: "sx-appDegreePageStyle13 ui-text-defined",
  appDegreePageStyle14: "sx-appDegreePageStyle14 ui-text-defined",
  appDegreePageStyle15: "sx-appDegreePageStyle15 ui-text-defined",
  appDegreePageStyle16: "sx-appDegreePageStyle16",
  appDegreePageStyle17: "sx-appDegreePageStyle17",
  appDegreePageStyle18: "sx-appDegreePageStyle18 ui-text-defined",
  appExplorePageStyle1: "sx-appExplorePageStyle1 ui-text-defined",
  appExplorePageStyle2: "sx-appExplorePageStyle2 ui-border-b",
  appExplorePageStyle3: "sx-appExplorePageStyle3",
  appExplorePageStyle4: "sx-appExplorePageStyle4",
  appExplorePageStyle5: "sx-appExplorePageStyle5 ui-text-defined",
  appExplorePageStyle6: "sx-appExplorePageStyle6",
  appExplorePageStyle7: "sx-appExplorePageStyle7 ui-text-defined",
  appExplorePageStyle9: "sx-appExplorePageStyle9",
  appLayoutStyle1: "sx-appLayoutStyle1 ui-text-defined",
  appMiniProjectsPageStyle8: "sx-appMiniProjectsPageStyle8",
  appMiniProjectsPageStyle9: "sx-appMiniProjectsPageStyle9 ui-text-defined",
  appMiniProjectsPageStyle19: "sx-appMiniProjectsPageStyle19",
  appMiniProjectsPageStyle20: "sx-appMiniProjectsPageStyle20 ui-text-defined",
  appMiniProjectsPageStyle21: "sx-appMiniProjectsPageStyle21 ui-text-defined",
  appMiniProjectsPageStyle22: "sx-appMiniProjectsPageStyle22 ui-text-defined",
  appMiniProjectsPageStyle24: "sx-appMiniProjectsPageStyle24",
  appMiniProjectsPageStyle25: "sx-appMiniProjectsPageStyle25 ui-text-defined",
  appMiniProjectsPageStyle26: "sx-appMiniProjectsPageStyle26 ui-text-defined",
  appMiniProjectsPageStyle36: "sx-appMiniProjectsPageStyle36 ui-text-defined",
  appMiniProjectsPageStyle58: "sx-appMiniProjectsPageStyle58 ui-text-defined",
  appMiniProjectsPageStyle59: "sx-appMiniProjectsPageStyle59 ui-text-defined",
  appMiniProjectsPageStyle60: "sx-appMiniProjectsPageStyle60 ui-text-defined",
  appMiniProjectsPageStyle61: "sx-appMiniProjectsPageStyle61 ui-text-defined",
  appNotFoundStyle1: "sx-appNotFoundStyle1 ui-text-defined",
  appNotFoundStyle2: "sx-appNotFoundStyle2 ui-text-defined",
  appNotFoundStyle3: "sx-appNotFoundStyle3",
  appNotFoundStyle4: "sx-appNotFoundStyle4",
  appNotFoundStyle5: "sx-appNotFoundStyle5 ui-text-defined",
  appNotFoundStyle7: "sx-appNotFoundStyle7 ui-text-defined",
  appNotFoundStyle9: "sx-appNotFoundStyle9",
  appNotFoundStyle11: "sx-appNotFoundStyle11",
  appNotFoundStyle14: "sx-appNotFoundStyle14 ui-border-t",
  appNotFoundStyle15: "sx-appNotFoundStyle15 ui-text-defined",
  appNotFoundStyle16: "sx-appNotFoundStyle16 ui-text-defined",
  appNotFoundStyle17: "sx-appNotFoundStyle17 ui-text-defined",
  appPageStyle1: "sx-appPageStyle1 ui-text-defined",
  appPageStyle2: "sx-appPageStyle2 ui-text-defined",
  appPageStyle4: "sx-appPageStyle4 ui-text-defined",
  appPageStyle5: "sx-appPageStyle5 ui-text-defined",
  appPageStyle6: "sx-appPageStyle6",
  appPageStyle7: "sx-appPageStyle7 ui-text-defined",
  appPageStyle8: "sx-appPageStyle8",
  appPageStyle10: "sx-appPageStyle10",
  appPageStyle11: "sx-appPageStyle11 ui-group ui-text-defined",
  appPageStyle12: "sx-appPageStyle12",
  appPageStyle13: "sx-appPageStyle13",
  appPageStyle20: "sx-appPageStyle20",
  appPageStyle21: "sx-appPageStyle21 ui-text-defined",
  appPageStyle22: "sx-appPageStyle22",
  appPageStyle23: "sx-appPageStyle23 ui-text-defined",
  appPageStyle24: "sx-appPageStyle24 ui-text-defined",
  appPageStyle25: "sx-appPageStyle25 ui-text-defined",
  appPageStyle26: "sx-appPageStyle26 ui-text-defined",
  appPageStyle27: "sx-appPageStyle27 ui-text-defined",
  appProjectWorkPageStyle22: "sx-appProjectWorkPageStyle22 ui-text-defined",
  appProjectWorkPageStyle23: "sx-appProjectWorkPageStyle23 ui-text-defined",
  appProjectWorkPageStyle24: "sx-appProjectWorkPageStyle24 ui-text-defined",
  componentsApiDocsPageStyle2: "sx-componentsApiDocsPageStyle2",
  componentsApiDocsPageStyle4: "sx-componentsApiDocsPageStyle4 ui-text-defined",
  componentsApiDocsPageStyle5: "sx-componentsApiDocsPageStyle5",
  componentsApiDocsPageStyle7: "sx-componentsApiDocsPageStyle7",
  componentsApiDocsPageStyle8: "sx-componentsApiDocsPageStyle8 ui-text-defined",
  componentsApiDocsPageStyle9: "sx-componentsApiDocsPageStyle9 ui-text-defined",
  componentsApiDocsPageStyle10: "sx-componentsApiDocsPageStyle10 ui-text-defined",
  componentsApiDocsPageStyle11: "sx-componentsApiDocsPageStyle11",
  componentsApiDocsPageStyle17: "sx-componentsApiDocsPageStyle17 ui-text-defined",
  componentsApiDocsPageStyle18: "sx-componentsApiDocsPageStyle18 ui-text-defined",
  componentsApiDocsPageStyle21: "sx-componentsApiDocsPageStyle21 ui-text-defined",
  componentsApiDocsPageStyle24: "sx-componentsApiDocsPageStyle24 ui-text-defined",
  componentsApiDocsPageStyle25: "sx-componentsApiDocsPageStyle25",
  componentsApiDocsPageStyle26: "sx-componentsApiDocsPageStyle26 ui-text-defined",
  componentsApiDocsPageStyle27: "sx-componentsApiDocsPageStyle27 ui-text-defined",
  componentsApiDocsPageStyle31: "sx-componentsApiDocsPageStyle31",
  componentsApiDocsPageStyle32: "sx-componentsApiDocsPageStyle32 ui-text-defined",
  componentsApiDocsPageStyle33: "sx-componentsApiDocsPageStyle33 ui-text-defined",
  componentsApiDocsPageStyle34: "sx-componentsApiDocsPageStyle34 ui-text-defined",
  componentsApiDocsPageStyle35: "sx-componentsApiDocsPageStyle35 ui-text-defined",
  componentsApiDocsPageStyle36: "sx-componentsApiDocsPageStyle36 ui-text-defined",
  componentsApiDocsPageStyle39: "sx-componentsApiDocsPageStyle39 ui-text-defined",
  componentsCommandMenuStyle1: "sx-componentsCommandMenuStyle1 ui-border-b",
  componentsCommandMenuStyle2: "sx-componentsCommandMenuStyle2",
  componentsCommandMenuStyle3: "sx-componentsCommandMenuStyle3 ui-text-defined",
  componentsCommandMenuStyle5: "sx-componentsCommandMenuStyle5",
  componentsCommandMenuStyle6: "sx-componentsCommandMenuStyle6 ui-text-defined",
  componentsCommandMenuStyle7: "sx-componentsCommandMenuStyle7 ui-text-defined",
  componentsCommandMenuStyle11: "sx-componentsCommandMenuStyle11 ui-text-defined",
  componentsCommandMenuStyle13: "sx-componentsCommandMenuStyle13 ui-text-defined",
  componentsCommandMenuStyle14: "sx-componentsCommandMenuStyle14 ui-text-defined",
  componentsCommandMenuStyle15: "sx-componentsCommandMenuStyle15 ui-text-defined",
  componentsCommandMenuStyle17: "sx-componentsCommandMenuStyle17 ui-text-defined",
  componentsCommandMenuStyle18: "sx-componentsCommandMenuStyle18 ui-text-defined",
  componentsCoursePageClientStyle5: "sx-componentsCoursePageClientStyle5",
  componentsCoursePageClientStyle6: "sx-componentsCoursePageClientStyle6 ui-text-defined",
  componentsCoursePageClientStyle12: "sx-componentsCoursePageClientStyle12 ui-text-defined",
  componentsCoursePageClientStyle16: "sx-componentsCoursePageClientStyle16 ui-text-defined",
  componentsCoursePageClientStyle17: "sx-componentsCoursePageClientStyle17 ui-text-defined",
  componentsExploreGraphStyle1: "sx-componentsExploreGraphStyle1",
  componentsExploreGraphStyle2: "sx-componentsExploreGraphStyle2 ui-text-defined",
  componentsGlobalLayoutStyle1: "sx-componentsGlobalLayoutStyle1",
  componentsNetworkGraphStyle1: "sx-componentsNetworkGraphStyle1",
  componentsNetworkGraphStyle2: "sx-componentsNetworkGraphStyle2",
  componentsNetworkGraphStyle3: "sx-componentsNetworkGraphStyle3",
  componentsNetworkGraphStyle5: "sx-componentsNetworkGraphStyle5 ui-text-defined",
  componentsNetworkGraphStyle6: "sx-componentsNetworkGraphStyle6 ui-text-defined",
  componentsNetworkGraphStyle7: "sx-componentsNetworkGraphStyle7 ui-border-t",
  componentsNetworkGraphStyle8: "sx-componentsNetworkGraphStyle8 ui-text-defined",
  componentsCourseActionsStyle1: "sx-componentsCourseActionsStyle1 ui-text-defined",
  componentsCourseActionsStyle3: "sx-componentsCourseActionsStyle3 ui-text-defined",
  componentsModeToggleStyle1: "sx-componentsModeToggleStyle1",
  componentsModeToggleStyle2: "sx-componentsModeToggleStyle2",
  componentsModeToggleStyle3: "sx-componentsModeToggleStyle3",
  badgevariantdefault: "sx-badgevariantdefault ui-text-defined",
  badgevariantsecondary: "sx-badgevariantsecondary ui-text-defined",
  badgevariantdestructive: "sx-badgevariantdestructive ui-text-defined",
  badgevariantoutline: "sx-badgevariantoutline ui-text-defined",
  badgeBase: "sx-badgeBase ui-text-defined",
  buttonvariantdefault: "sx-buttonvariantdefault ui-text-defined",
  buttonvariantdestructive: "sx-buttonvariantdestructive ui-text-defined",
  buttonvariantoutline: "sx-buttonvariantoutline ui-text-defined",
  buttonvariantsecondary: "sx-buttonvariantsecondary ui-text-defined",
  buttonvariantghost: "sx-buttonvariantghost ui-text-defined",
  buttonvariantlink: "sx-buttonvariantlink ui-text-defined",
  buttonsizedefault: "sx-buttonsizedefault",
  buttonsizesm: "sx-buttonsizesm",
  buttonsizelg: "sx-buttonsizelg",
  buttonsizeicon: "sx-buttonsizeicon ui-size-defined",
  buttonsizeicon_sm: "sx-buttonsizeicon_sm ui-size-defined",
  buttonsizeicon_lg: "sx-buttonsizeicon_lg ui-size-defined",
  buttonBase: "sx-buttonBase ui-text-defined",
  componentsUiCardStyle1: "sx-componentsUiCardStyle1 ui-text-defined",
  componentsUiCardStyle2: "sx-componentsUiCardStyle2",
  componentsUiCardStyle3: "sx-componentsUiCardStyle3",
  componentsUiCardStyle5: "sx-componentsUiCardStyle5",
  componentsUiCardStyle6: "sx-componentsUiCardStyle6",
  componentsUiCardStyle7: "sx-componentsUiCardStyle7",
  componentsUiCommandStyle1: "sx-componentsUiCommandStyle1 ui-text-defined",
  componentsUiCommandStyle3: "sx-componentsUiCommandStyle3",
  componentsUiCommandStyle4: "sx-componentsUiCommandStyle4",
  componentsUiCommandStyle5: "sx-componentsUiCommandStyle5 ui-border-b",
  componentsUiCommandStyle6: "sx-componentsUiCommandStyle6 ui-size-defined",
  componentsUiCommandStyle7: "sx-componentsUiCommandStyle7 ui-text-defined",
  componentsUiCommandStyle8: "sx-componentsUiCommandStyle8",
  componentsUiCommandStyle9: "sx-componentsUiCommandStyle9 ui-text-defined",
  componentsUiCommandStyle10: "sx-componentsUiCommandStyle10 ui-text-defined",
  componentsUiCommandStyle11: "sx-componentsUiCommandStyle11",
  componentsUiCommandStyle12: "sx-componentsUiCommandStyle12 ui-text-defined",
  componentsUiCommandStyle13: "sx-componentsUiCommandStyle13 ui-text-defined",
  componentsUiDialogStyle1: "sx-componentsUiDialogStyle1",
  componentsUiDialogStyle2: "sx-componentsUiDialogStyle2",
  componentsUiDialogStyle3: "sx-componentsUiDialogStyle3",
  componentsUiDialogStyle5: "sx-componentsUiDialogStyle5 ui-text-defined",
  componentsUiDialogStyle6: "sx-componentsUiDialogStyle6",
  componentsUiDialogStyle7: "sx-componentsUiDialogStyle7 ui-text-defined",
  componentsUiInputStyle1: "sx-componentsUiInputStyle1 ui-text-defined",
  scrollVertical: "sx-scrollVertical",
  scrollHorizontal: "sx-scrollHorizontal ui-border-t",
  componentsUiScrollAreaStyle1: "sx-componentsUiScrollAreaStyle1",
  componentsUiScrollAreaStyle2: "sx-componentsUiScrollAreaStyle2 ui-size-defined",
  componentsUiScrollAreaStyle3: "sx-componentsUiScrollAreaStyle3",
  componentsUiSeparatorStyle1: "sx-componentsUiSeparatorStyle1",
};

/** Compose atomic styles with the semantic markers used by compound selectors. */
export function styleClass(
  key: keyof typeof styles,
  override?: stylex.StyleXStyles<Record<string, string | number | null>>,
) {
  return [stylex.props(styles[key], override).className, markers[key]].filter(Boolean).join(" ");
}
